=== jiangyuanjian/jsnapp/trunk/conf/server.dtd
<!--==========================================-->
<!-- Top configuration element                -->
<!--==========================================-->

<!ELEMENT configuration (internal, databases, listeners, workers, keystore?)>
<!ATTLIST configuration
	watchdog CDATA #REQUIRED
>

<!--==========================================-->
<!-- Internal database configuration        -->
<!--==========================================-->

<!ELEMENT internal (driver, url, pool, idle)>

<!ELEMENT driver (#PCDATA)>

<!ELEMENT url (#PCDATA)>

<!ELEMENT pool (#PCDATA)>

<!ELEMENT idle (#PCDATA)>

<!--==========================================-->
<!-- Database configuration                   -->
<!--==========================================-->

<!ELEMENT databases (database*)>

<!ELEMENT database (driver, url, pool, idle, initial, increment, multiplier, login, accesscontrol)>
<!ATTLIST database
	name ID #REQUIRED
>

<!--ELEMENT driver (#PCDATA) already defined -->

<!--ELEMENT url (#PCDATA) already defined -->

<!--ELEMENT pool (#PCDATA) already defined -->

<!--ELEMENT idle (#PCDATA) already defined -->

<!ELEMENT initial (#PCDATA)>

<!ELEMENT increment (#PCDATA)>

<!ELEMENT multiplier (#PCDATA)>

<!ELEMENT login (#PCDATA)>

<!ELEMENT accesscontrol (#PCDATA)>

<!--==========================================-->
<!-- Listener configuration                   -->
<!--==========================================-->

<!ELEMENT listeners (listener*)>

<!ELEMENT listener (port, backlog, accepts)>

<!ELEMENT port (#PCDATA)>

<!ELEMENT backlog (#PCDATA)>

<!ELEMENT accepts (#PCDATA)>

<!--==========================================-->
<!-- Worker configuration                     -->
<!--==========================================-->

<!ELEMENT workers (core, max, idle)>

<!ELEMENT core (#PCDATA)>

<!ELEMENT max (#PCDATA)>

<!--ELEMENT idle (#PCDATA) already defined -->

<!--==========================================-->
<!-- Keystore configuration                   -->
<!--==========================================-->

<!ELEMENT keystore (url, password)>

<!--ELEMENT url (#PCDATA) already defined -->

<!ELEMENT password (#PCDATA)>

=== jiangyuanjian/jsnapp/trunk/conf/server.xml
<!DOCTYPE configuration SYSTEM "conf/server.dtd">
<configuration watchdog="1">
	<internal>
		<!--driver>org.hsqldb.jdbcDriver</driver-->
		<!--url>jdbc:hsqldb:file:/home/reha/temp/internaldb</url-->
		<driver>org.postgresql.Driver</driver>
		<url>jdbc:postgresql:internal?user=jsnap&amp;password=passw0rd</url>
		<pool>20</pool>
		<idle>600</idle>
	</internal>
	<databases>
		<database name="postgres">
			<driver>org.jsnap.db.Postgres</driver>
			<url>jdbc:postgresql:jsnapdev?user=jsnap&amp;password=passw0rd</url>
			<pool>20</pool>
			<idle>600</idle>
			<initial>60</initial>
			<increment>30</increment>
			<multiplier>0</multiplier>
			<login>org.jsnap.security.Authenticate</login>
			<accesscontrol>org.jsnap.security.AllowAll</accesscontrol>
		</database>
		<database name="hsqldb">
			<driver>org.hsqldb.jdbcDriver</driver>
			<url>jdbc:hsqldb:file:/home/reha/temp/internaldb</url>
			<pool>20</pool>
			<idle>600</idle>
			<initial>60</initial>
			<increment>30</increment>
			<multiplier>0</multiplier>
			<login>org.jsnap.security.Authenticate</login>
			<accesscontrol>org.jsnap.security.AllowAll</accesscontrol>
		</database>
	</databases>
	<listeners>
        <!-- Web Console -->
        <listener>
          <port>8080</port>
          <backlog>5</backlog>
          <accepts>org.jsnap.http.WebConsoleRequest</accepts>
        </listener>
        <listener>
          <port>8090</port>
          <backlog>5</backlog>
          <accepts>org.jsnap.http.PasswordRenewalRequest</accepts>
        </listener>
		<listener>
			<port>52660</port>
			<backlog>100</backlog>
			<accepts>org.jsnap.request.SizePackedRequest</accepts>
		</listener>
		<listener>
			<port>52661</port>
			<backlog>100</backlog>
			<accepts>org.jsnap.request.HttpRequest</accepts>
		</listener>
		<listener>
			<port>52662</port>
			<backlog>100</backlog>
			<accepts>org.jsnap.request.SizePackedSecureRequest</accepts>
		</listener>
		<listener>
			<port>52663</port>
			<backlog>100</backlog>
			<accepts>org.jsnap.request.SSLRequest</accepts>
		</listener>
	</listeners>
	<workers>
		<core>0</core>
		<max>100</max>
		<idle>300</idle>
	</workers>
	<keystore>
		<url>conf/jsnap.keystore</url>
		<password>passw0rd</password>
	</keystore>
</configuration>
